---
title: "GOM tracer pre-processing"
output:
  html_document: 
    code_fold: hide
    toc: yes
    toc_float: true
---

```{r setup, echo=F, message=FALSE, warning=FALSE}

library(tidyverse)
library(magrittr)
library(readxl)
library(fastinR)
library(vegan)
library(knitr)

opts_chunk$set(warning=FALSE,message=FALSE,tidy=FALSE,fig.width = 12,fig.height=8,dpi = 150)
#options(replace.assign=TRUE,width=50)

```

# Pre-processing

```{r data}

BC    <- read_xlsx('data/CWCIII modelling workshop FASTIN R data.xlsx',sheet = 1, na = 'NA')
Killi <- read_xlsx('data/CWCIII modelling workshop FASTIN R data.xlsx',sheet = 2, na = 'NA')
AtlCr <- read_xlsx('data/CWCIII modelling workshop FASTIN R data.xlsx',sheet = 3, na = 'NA')

pred <- bind_rows(BC, Killi, AtlCr, .id = 'Predator')
predators <- c('Blue Crab', 'Killifish', 'Atlantic Croaker')
pred$Predator <- predators[as.numeric(pred$Predator)]

BC_prey    <- read_xlsx('data/CWCIII modelling workshop FASTIN R data.xlsx',sheet = 5, na = 'NA')
Killi_prey <- read_xlsx('data/CWCIII modelling workshop FASTIN R data.xlsx',sheet = 6, na = 'NA')
AtlCr_prey <- read_xlsx('data/CWCIII modelling workshop FASTIN R data.xlsx',sheet = 7, na = 'NA')

prey <- bind_rows(BC_prey, Killi_prey, AtlCr_prey, .id = 'Predator')
prey$Predator <- predators[as.numeric(prey$Predator)]

SI_cols <- which(colnames(prey) %in% c('d13C', 'd15N'))
FA_cols <- grep('[1-9]{2}_.',colnames(prey))

groups <- read_xlsx('data/CWC food web groups.xlsx')

PP <- bind_rows(pred, prey, .id = 'PP')
PP$PP <- c('Pred','Prey')[as.numeric(PP$PP)]

PP_SI_cols <- which(colnames(PP) %in% c('d13C', 'd15N'))
PP_FA_cols <- grep('[1-9]{2}_.',colnames(PP))

selecta <- rowSums(!is.na(PP[,PP_FA_cols]))>0 & rowSums(!is.na(PP[,PP_SI_cols]))>0

PP %<>% filter(selecta)
PP <- PP[, colSums(!is.na(PP)) == nrow(PP) | colnames(PP) %in% c('d13C', 'd15N')]
PP <- PP[,-which(colnames(PP)=='18_2n6c')]
FA_cols <- grep('[1-9]{2}_.',colnames(PP))
SI_cols <- which(colnames(PP) %in% c('d13C', 'd15N'))

for (i in FA_cols) PP[PP[,i]==0,i] <- 0.01;#min(PP[PP[,i]>0,i], na.rm=T)

PP$Species <- gsub("0",'nd',PP$Species)
PP$Habitat_Location <- gsub("0",'nd',PP$Habitat_Location)
PP$Genus <- word(PP$Species)
ss <- sapply(PP$Genus, grep, groups$`CWC species`)
PP$IX <- unlist(lapply(ss, function(x) if (length(x) == 0) {NA} else {x}))
PP$`EwE group` = groups$`CWC3 Ecopath Group`[PP$IX]

PP %<>% mutate(`EwE group` = ifelse(!is.na(`EwE group`), `EwE group`, `Species`))

```

# Calibration coeffs

```{r}

bluecrab_cc <- read_csv('data/calibration_coefficient_summary_d84.csv')

ggplot(bluecrab_cc) + 
  geom_pointrange(aes(x=FA, y=avg_CC, ymax=avg_CC+SD_CC, ymin=avg_CC-SD_CC, col=diet)) + 
  scale_y_log10() + 
  cowplot::theme_cowplot() + 
  geom_hline(yintercept = 1, linetype=3) + 
  ylab("Conv. Coeff.") + 
  theme(axis.text.x = element_text(angle=45,hjust=1),
        panel.grid.major.x = element_line(linetype = 3),
        panel.grid.minor.x = element_line(linetype = 3))

final_CC <- bluecrab_cc %>% 
  mutate(FA = sub(":","_",FA),
         FA = gsub("-","",FA),
         FA = sub("trans","t",FA),
         FA = sub("cis","c",FA)) %>%
  group_by(FA,diet,tissue) %>%
  #nest() %>%
  mutate(FAL = any(grepl(FA, colnames(PP)[FA_cols]))) %>%
  filter(avg_diet>0.05, FAL) %>%
  mutate(FAS = grep(FA, colnames(PP)[FA_cols],value = T)) %>%
  group_by(FAS) %>%
  summarise(avg_CC = weighted.mean(avg_CC, w=SD_CC),
            SD_CC = mean(SD_CC)) %>%
  mutate(FA = factor(FAS, levels = colnames(PP)[FA_cols])) %>%
  complete(FA, fill = list(avg_CC = 1,
                           SD_CC  = 2)) %>%
  select(-FAS)


ggplot(final_CC) + 
  geom_pointrange(aes(x=FA, y=avg_CC, ymax=avg_CC+SD_CC, ymin=avg_CC-SD_CC)) + 
  #scale_y_log10() + 
  cowplot::theme_cowplot() + 
  geom_hline(yintercept = 1, linetype=3) + 
  ylab("Conv. Coeff.") + 
  theme(axis.text.x = element_text(angle=45,hjust=1))


croaker_cc <- read_csv('data/calibration_coefficient_croaker.csv')

ggplot(croaker_cc) + 
  geom_pointrange(aes(x=FA, y=Muscle, ymax=Muscle+SD, ymin=Muscle-SD)) + 
  scale_y_log10() + 
  cowplot::theme_cowplot() + 
  geom_hline(yintercept = 1, linetype=3) + 
  ylab("Conv. Coeff.") + 
  theme(axis.text.x = element_text(angle=45,hjust=1))

Croaker_CC <- croaker_cc %>% 
  mutate(FA = sub(":","_",FA),
         FA = gsub("-","",FA)) %>% 
  pull(FA) 

clist <- sapply(1:length(Croaker_CC),function(i) {
  val = grep(Croaker_CC[i],colnames(PP)[FA_cols], value=T)
  if(length(val)>0) data.frame(FA=val,avg_CC = croaker_cc$Muscle[i],SD_CC = croaker_cc$SD[i])})

Croaker_CC <- do.call(rbind,clist)

Croaker_CC %<>%
  mutate(FA = factor(FA, levels = colnames(PP)[FA_cols])) %>%
  complete(FA, fill = list(avg_CC = 1,
                           SD_CC  = 2))


cc_list <- list('Blue Crab' = final_CC,
                'Atlantic croaker' = Croaker_CC)


bind_rows(cc_list, .id = 'Predator') %>%
  ggplot() + 
  geom_pointrange(aes(x=FA, y=avg_CC, ymax=qgamma(0.95,shape = avg_CC^2/SD_CC^2, rate = avg_CC/SD_CC^2), ymin=qgamma(0.05,shape = avg_CC^2/SD_CC^2, rate = avg_CC/SD_CC^2), col=Predator)) + 
  #scale_y_log10() + 
  cowplot::theme_cowplot() + 
  geom_hline(yintercept = 1, linetype=3) + 
  ylab("Conv. Coeff.") + 
  theme(axis.text.x = element_text(angle=45,hjust=1))



```

# Model setup

```{r}

PP %<>% mutate(gr_site = substr(Site,1,2))
PP %<>% ungroup() %>% mutate(prey.ix = paste(`EwE group`)) %>% group_by(PP,Predator,prey.ix,gr_site) %>% filter(PP=='Pred' | (PP=='Prey' & n()>=3))

get_prey <- function(Pred, Site){
  #browser()
  PP %>% filter(Predator == Pred,
                PP == 'Prey') %>% 
    group_by(prey.ix) %>%
    mutate(keep = any(gr_site==!!Site)) %>% 
    ungroup() %>% 
    mutate(keep = ifelse(keep,gr_site,!!Site)) %>% 
    filter(keep == !!Site) %>%
    mutate(prey.ix = paste(`EwE group`,gr_site)) %>% 
    arrange(prey.ix)
}


FA_args <- list(nIter=25000,
                nBurnin=5000,
                nChains=8,
                nThin=80,
                Data.Type='Combined.Analysis',
                Analysis.Type='Population.proportions',
                Rnot=0.2,plott=F,spawn=F)

```

# Blue crab

```{r}

BC_PS_pred <- PP %>% filter(Predator == 'Blue Crab',
                            PP == 'Pred',
                            gr_site=='PS')

BC_PS_prey <- get_prey(Pred = 'Blue Crab', Site = 'PS') %>% filter(!grepl('Blue crabs',prey.ix))

BC.data.PS <- add_FA(FA.predators = as.matrix(BC_PS_pred[, FA_cols]),
                     FA.preys     = data.frame(BC_PS_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]),
                     CC.mean = cc_list$`Blue Crab`$avg_CC,
                     CC.var  = cc_list$`Blue Crab`$SD_CC)


BC.data.PS <- add_SI(SI.predators = as.matrix(BC_PS_pred[, SI_cols]),
                     SI.preys     = data.frame(BC_PS_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                     FC.mean = c(-0.5, 1),
                     FC.var  = c(1, 1),
                     datas=BC.data.PS)


BC_WP_pred <- PP %>% filter(Predator == 'Blue Crab',
                            PP == 'Pred',
                            gr_site=='WP')

BC_WP_prey <- get_prey(Pred = 'Blue Crab', Site = 'WP') %>% filter(!grepl('Blue crabs',prey.ix))

BC.data.WP <- add_FA(FA.predators = as.matrix(BC_WP_pred[, FA_cols]),
                     FA.preys     = data.frame(BC_WP_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]),
                     CC.mean = cc_list$`Blue Crab`$avg_CC,
                     CC.var  = cc_list$`Blue Crab`$SD_CC)


BC.data.WP <- add_SI(SI.predators = as.matrix(BC_WP_pred[, SI_cols]),
                     SI.preys     = data.frame(BC_WP_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                     FC.mean = c(-0.5, 1),
                     FC.var  = c(1, 1),
                     datas=BC.data.WP)



BC_vs_BC_PS_prey <- get_prey(Pred = 'Blue Crab', Site = 'PS')

BCvsBC.data.PS <- add_FA(FA.predators = as.matrix(BC_PS_pred[, FA_cols]),
                         FA.preys     = data.frame(BC_vs_BC_PS_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]),
                         CC.mean = cc_list$`Blue Crab`$avg_CC,
                         CC.var  = cc_list$`Blue Crab`$SD_CC)


BCvsBC.data.PS <- add_SI(SI.predators = as.matrix(BC_PS_pred[, SI_cols]),
                         SI.preys     = data.frame(BC_vs_BC_PS_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                         FC.mean = c(-0.5, 1),
                         FC.var  = c(1, 1),
                         datas=BCvsBC.data.PS)



BC_vs_BC_WP_prey <- get_prey(Pred = 'Blue Crab', Site = 'WP')

BCvsBC.data.WP <- add_FA(FA.predators = as.matrix(BC_WP_pred[, FA_cols]),
                         FA.preys     = data.frame(BC_vs_BC_WP_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]),
                         CC.mean = cc_list$`Blue Crab`$avg_CC,
                         CC.var  = cc_list$`Blue Crab`$SD_CC)


BCvsBC.data.WP <- add_SI(SI.predators = as.matrix(BC_WP_pred[, SI_cols]),
                         SI.preys     = data.frame(BC_vs_BC_WP_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                         FC.mean = c(-0.5, 1),
                         FC.var  = c(1, 1),
                         datas=BCvsBC.data.WP)

```

## Model
### Blue crab PS

```{r model0}

FAS_BC_PS <- which(colnames(BCvsBC.data.PS$datas.FA$preds.FA) %in% c('18_1n9c',
                                                                     '18_3n3',
                                                                     '22_6n3',
                                                                     '16_1n7',
                                                                     '16_0',
                                                                     '18_1n9t',
                                                                     '18_1n7',
                                                                     '18_0',
                                                                     '18_3n6'))

BC.data.PS.sub <- fastinR::select_vars(BC.data.PS, FAS_BC_PS)
par(mfrow=c(2,1))
dataplot(BC.data.PS)
dataplot(BC.data.PS.sub)

FA_args$datas <- BC.data.PS.sub
BC.data.PS.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(BC.data.PS.mod$res)
diags(BC.data.PS.mod$res)
BC.data.PS.mod$res
plot.pop_props(BC.data.PS.mod$res,save=F,density=F,types = 'post')

```

### Blue crab WP

```{r}

FAS_BC_WP <- which(colnames(BCvsBC.data.WP$datas.FA$preds.FA) %in% c('18_1n9c',
                                                                     '18_3n3',
                                                                     '22_6n3',
                                                                     '16_1n7',
                                                                     '16_0',
                                                                     '18_1n9t',
                                                                     '18_1n7'))

BC.data.WP.sub <- fastinR::select_vars(BC.data.WP, FAS_BC_WP)
par(mfrow=c(2,1))
dataplot(BC.data.WP.sub)
dataplot(BC.data.WP)


FA_args$datas <- BC.data.WP.sub
BC.data.WP.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(BC.data.WP.mod$res)
diags(BC.data.WP.mod$res)
BC.data.WP.mod$res
plot.pop_props(BC.data.WP.mod$res,save=F,density = F)

plot(BC.data.PS.mod$mod,pars='cc') + geom_vline(xintercept=qnorm(0.025,1,1), linetype=2) + geom_vline(xintercept=qnorm(0.975,1,1), linetype=2)
```

### Blue crab PS with BC prey
```{r}
##################################
###### Same with BC prey #########
##################################

BCvsBC.data.PS.sub <- fastinR::select_vars(BCvsBC.data.PS, FAS_BC_PS)
par(mfrow=c(2,1))
dataplot(BCvsBC.data.PS)
dataplot(BCvsBC.data.PS.sub)

FA_args$datas <- BCvsBC.data.PS.sub
BCvsBC.data.PS.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(BCvsBC.data.PS.mod$res)
diags(BCvsBC.data.PS.mod$res)
BCvsBC.data.PS.mod$res
plot.pop_props(BCvsBC.data.PS.mod$res,save=F,density=F,types = 'post')

```

### Blue crab WP with BC prey

```{r}

BCvsBC.data.WP.sub <- fastinR::select_vars(BCvsBC.data.WP, FAS_BC_WP)
par(mfrow=c(2,1))
dataplot(BCvsBC.data.WP.sub)
dataplot(BCvsBC.data.WP)

FA_args$datas <- BCvsBC.data.WP.sub
BCvsBC.data.WP.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(BCvsBC.data.WP.mod$res)
diags(BCvsBC.data.WP.mod$res)
BCvsBC.data.WP.mod$res
plot.pop_props(BCvsBC.data.WP.mod$res,save=F,density = F)

plot(BCvsBC.data.PS.mod$mod,pars='cc') + geom_vline(xintercept=qnorm(0.025,1,1), linetype=2) + geom_vline(xintercept=qnorm(0.975,1,1), linetype=2)


```

# Killifish

```{r}

KF_PS_pred <- PP %>% filter(Predator == 'Killifish',
                            PP == 'Pred',
                            gr_site=='PS')

KF_PS_prey <- get_prey(Pred = 'Killifish', Site = 'PS') %>% filter(!grepl('Menhaden',prey.ix))

KF.data.PS <- add_FA(FA.predators = as.matrix(KF_PS_pred[, FA_cols]),
                     FA.preys     = data.frame(KF_PS_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]))


KF.data.PS <- add_SI(SI.predators = as.matrix(KF_PS_pred[, SI_cols]),
                     SI.preys     = data.frame(KF_PS_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                     FC.mean = c(-0.5, 1),
                     FC.var  = c(1, 1),
                     datas=KF.data.PS)


KF_WP_pred <- PP %>% filter(Predator == 'Killifish',
                            PP == 'Pred',
                            gr_site=='WP')

KF_WP_prey <- get_prey(Pred = 'Killifish', Site = 'WP') %>% filter(!grepl('Menhaden',prey.ix))

KF.data.WP <- add_FA(FA.predators = as.matrix(KF_WP_pred[, FA_cols]),
                     FA.preys     = data.frame(KF_WP_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]))


KF.data.WP <- add_SI(SI.predators = as.matrix(KF_WP_pred[, SI_cols]),
                     SI.preys     = data.frame(KF_WP_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                     FC.mean = c(-0.5, 1),
                     FC.var  = c(1, 1),
                     datas=KF.data.WP)

```

## Model
### Killifish PS
```{r model1}

FAS <- which(colnames(KF.data.PS$datas.FA$preds.FA) %in% c('18_1n9c',
                                                           '16_1n7',
                                                           '22_6n3',
                                                           '16_0',
                                                           '18_1n7',
                                                           '18_0',
                                                           '24_0',
                                                           '24_1n9',
                                                           '18_3n3'))

KF.data.PS.sub <- fastinR::select_vars(KF.data.PS, FAS)
par(mfrow=c(2,1))
dataplot(KF.data.PS)
dataplot(KF.data.PS.sub)

FA_args$datas <- KF.data.PS.sub

KF.data.PS.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(KF.data.PS.mod$res)
diags(KF.data.PS.mod$res)
KF.data.PS.mod$res
plot.pop_props(KF.data.PS.mod$res,save=F,density=F, type='post')

```

### Killifish WP

```{r}
FAS <- which(colnames(KF.data.WP$datas.FA$preds.FA) %in% c('18_1n9c',
                                                           '18_3n3',
                                                           '22_6n3',
                                                           '16_1n7',
                                                           '18_1n7',
                                                           '18_0',
                                                           '24_0',
                                                           '16_0'
                                                           ))

KF.data.WP.sub <- fastinR::select_vars(KF.data.WP, FAS)
par(mfrow=c(2,1))
dataplot(KF.data.WP.sub)
dataplot(KF.data.WP)

FA_args$datas <- KF.data.WP.sub

KF.data.WP.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(KF.data.WP.mod$res)
diags(KF.data.WP.mod$res)
KF.data.WP.mod$res
plot.pop_props(KF.data.WP.mod$res,save=F,density = F)

```

# Atlantic Croaker

```{r}

AC_PS_pred <- PP %>% filter(Predator == 'Atlantic Croaker',
                            PP == 'Pred',
                            gr_site=='PS')

AC_PS_prey <- get_prey(Pred = 'Atlantic Croaker', Site = 'PS')

AC.data.PS <- add_FA(FA.predators = as.matrix(AC_PS_pred[, FA_cols]),
                     FA.preys     = data.frame(AC_PS_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]),
                     CC.mean = cc_list$`Atlantic croaker`$avg_CC,
                     CC.var  = cc_list$`Atlantic croaker`$SD_CC)


AC.data.PS <- add_SI(SI.predators = as.matrix(AC_PS_pred[, SI_cols]),
                     SI.preys     = data.frame(AC_PS_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                     FC.mean = c(-0.5, 1),
                     FC.var  = c(1, 1),
                     datas=AC.data.PS)


AC_WP_pred <- PP %>% filter(Predator == 'Atlantic Croaker',
                            PP == 'Pred',
                            gr_site=='WP')

AC_WP_prey <- get_prey(Pred = 'Atlantic Croaker', Site = 'WP')

AC.data.WP <- add_FA(FA.predators = as.matrix(AC_WP_pred[, FA_cols]),
                     FA.preys     = data.frame(AC_WP_prey[,c(which(colnames(PP)=='prey.ix'),FA_cols)]),
                     CC.mean = cc_list$`Atlantic croaker`$avg_CC,
                     CC.var  = cc_list$`Atlantic croaker`$SD_CC)


AC.data.WP <- add_SI(SI.predators = as.matrix(AC_WP_pred[, SI_cols]),
                     SI.preys     = data.frame(AC_WP_prey[,c(which(colnames(PP)=='prey.ix'),SI_cols)]),
                     FC.mean = c(-0.5, 1),
                     FC.var  = c(1, 1),
                     datas=AC.data.WP)

```

## Atlantic Croaker Model
### Atlantic Croaker PS
```{r model2}


FAS <- which(colnames(AC.data.PS$datas.FA$preds.FA) %in% c('18_1n9c',
                                                           '22_6n3',
                                                           '24_0',
                                                           '16_0',
                                                           '18_0',
                                                           '16_1n7'#,
                                                            #'18_1n7',
                                                           #'17_0',
                                                           #'22_0',
                                                           #'18_1n9t'
                                                           ))

AC.data.PS.sub <- fastinR::select_vars(AC.data.PS, FAS)
par(mfrow=c(2,1))
dataplot(AC.data.PS)
dataplot(AC.data.PS.sub)

FA_args$datas <- AC.data.PS.sub

AC.data.PS.mod <- brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(AC.data.PS.mod$res)
diags(AC.data.PS.mod$res)
AC.data.PS.mod$res
plot.pop_props(AC.data.PS.mod$res,save=F,density=F, type='post')

```


### Atlantic Croaker WP
```{r}


FAS <- which(colnames(AC.data.WP$datas.FA$preds.FA) %in% c('18_1n9c',
                                                           '24_0',
                                                           '22_6n3',
                                                           '16_1n7',
                                                           '16_0',
                                                           '18_0'
                                                           #'17_0',
                                                           #'22_0'
                                                           #'18_1n9t'
                                                           ))

AC.data.WP.sub <- fastinR::select_vars(AC.data.WP, FAS)
par(mfrow=c(2,1))
dataplot(AC.data.WP.sub)
dataplot(AC.data.WP)

FA_args$datas <- AC.data.WP.sub

AC.data.WP.mod <-  brms:::eval_silent(do.call(run_MCMC, FA_args), type='message')
#diagnostics
MCMCplot(AC.data.WP.mod$res)
diags(AC.data.WP.mod$res)
AC.data.WP.mod$res
plot.pop_props(AC.data.WP.mod$res,save=F,density = F, type='post')

```


```{r}

modlist <- list('Blue crab PS - no BC prey' = list(mod  = BC.data.PS.mod$mod,
                                                   prey = BC.data.PS.mod$res$prey.names),
                'Blue crab WPH - no BC prey' = list(mod  = BC.data.WP.mod$mod,
                                                    prey = BC.data.WP.mod$res$prey.names),
                'Blue crab PS - with BC prey' = list(mod  = BCvsBC.data.PS.mod$mod,
                                                     prey = BCvsBC.data.PS.mod$res$prey.names),
                'Blue crab WPH - with BC prey' = list(mod  = BCvsBC.data.WP.mod$mod,
                                                      prey = BCvsBC.data.WP.mod$res$prey.names))

out <- lapply(modlist, function(l) {
  props <- rstan::extract(l$mod,pars='prop')$prop
  colnames(props) <- l$prey
  reshape2::melt(props)
}) %>% bind_rows(.id = 'Species')

colnames(out)[2:3] <- c('iter', 'Prey')

out %<>%
  mutate(Prey = gsub(' PS','',Prey),
         Prey = gsub(' WP','',Prey)) %>%
  group_by(Species, Prey) %>%
  summarise(m = mean(value),
            q11 = quantile(value, 0.025),
            q1 = quantile(value, 0.1),
            q3 = quantile(value, 0.9),
            q33 = quantile(value, 0.975))

ggplot(out) +
  geom_pointrange(aes(x=Prey, y=m, ymin=q11, ymax=q33, col=Prey), size=0.5) +
  geom_linerange(aes(x=Prey, y=m, ymin=q1, ymax=q3, col=Prey), size=1) +
  facet_wrap(~Species, ncol = 2) +
  coord_flip() +
  cowplot::theme_cowplot() +
  scale_color_discrete(guide='none') +
  ylab('Prey proportion') +
  theme(axis.text.y = element_text(size=8))

```

```{r}

modlist <- list('Blue crab PS' = list(mod  = BCvsBC.data.PS.mod$mod,
                                      prey = BCvsBC.data.PS.mod$res$prey.names),
                'Blue crab WPH' = list(mod  = BCvsBC.data.WP.mod$mod,
                                       prey = BCvsBC.data.WP.mod$res$prey.names),
                'Killifish PS' = list(mod  = KF.data.PS.mod$mod,
                                      prey = KF.data.PS.mod$res$prey.names),
                'Killifish WPH' = list(mod  = KF.data.WP.mod$mod,
                                       prey = KF.data.WP.mod$res$prey.names),
                'Atlantic Croaker PS' = list(mod  = AC.data.PS.mod$mod,
                                             prey = AC.data.PS.mod$res$prey.names),
                'Atlantic Croaker WPH' = list(mod  = AC.data.WP.mod$mod,
                                              prey = AC.data.WP.mod$res$prey.names))

out <- lapply(modlist, function(l) {
  props <- rstan::extract(l$mod,pars='prop')$prop
  colnames(props) <- l$prey
  reshape2::melt(props)
}) %>% bind_rows(.id = 'Species')

colnames(out)[2:3] <- c('iter', 'Prey')

out %<>%
  mutate(Prey = gsub(' PS','',Prey),
         Prey = gsub(' WP','',Prey)) %>%
  group_by(Species, Prey) %>%
  summarise(m = mean(value),
            q11 = quantile(value, 0.025),
            q1 = quantile(value, 0.1),
            q3 = quantile(value, 0.9),
            q33 = quantile(value, 0.975))

ggplot(out) +
  geom_pointrange(aes(x=Prey, y=m, ymin=q11, ymax=q33, col=Prey), size=0.5) +
  geom_linerange(aes(x=Prey, y=m, ymin=q1, ymax=q3, col=Prey), size=1) +
  facet_wrap(~Species, ncol = 2, scales = 'free_y') +
  coord_flip() +
  cowplot::theme_cowplot() +
  scale_color_discrete(guide='none') +
  ylab('Prey proportion') +
  theme(axis.text.y = element_text(size=8))

```

```{r}
save(out,file = 'GoM_diet_props.Rdata')
save.image(file = 'GoM_tracers.Rdata')
```


